import Head from 'next/head'
import styles from "../../styles/rider/RiderHome.module.css";
import Navsidebar from '@/components/rider/Navsidebarr';

import Orderstatus from '@/components/rider/orderstatus';
import Orderbox from '@/components/rider/orderbox';
import axios from 'axios';
import { getServer } from '@/config';
import { useRequireAuth } from './auth';





export default function Home({records}) {

  const session = useRequireAuth();

  return (
   
    <>
    {session ? (
      <><Head>
          <title>Get Pills</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/Getpills black.png" />
        </Head><div className={styles.home}>
            <Navsidebar />
            <Orderbox records={records} />
            {/* <Orderstatus/> */}


          </div></>
      ) : (
        // Render content when the user is not authenticated
        <div>
          <alert>session expired! try to login to access page!</alert>
  
          {/* Render login form or redirect to the login page */}
        </div>
      )}
   </>
  )
}


export const getServerSideProps = async () => {
  const deliveryRes = await axios.get(`${getServer}/api/Delivery`);
  console.log(deliveryRes.data, "res")
  return {
    props: {
      records: deliveryRes.data,
    },
  };
};
