import Head from 'next/head'
import styles from "../../styles/rider/RiderHome.module.css";
import Navsidebar from '@/components/rider/Navsidebarr';

import Orderstatus from '@/components/rider/orderstatus';
import Orderbox from '@/components/rider/orderbox';





export default function Home() {
  return (
    <>
      <Head>
        <title>Get Pills</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Getpills black.png" />
      </Head>
      <div className={styles.home}>
       <Navsidebar/>
       <Orderbox />
       <Orderstatus/>

   
        </div>
    
   </>
  )
}
