import Head from "next/head";
import styles from "../../styles/rider/Login.module.css";

export default function LoginForm() {
  return (
    <>
      <Head>
        <title>Get Pills</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.LogDiv}>
        <form className={styles.LogForm}>
          <label for="rider" className={styles.rider}>
            RIDER
          </label>
          <label for="Mail" className={styles.MailText}>
            Email
          </label>
          <input
            type="email"
            id="email"
            name="mail"
            className={styles.maily}
            placeholder="newuser@gmail.com"
            required
          />

          <label for="Pass" className={styles.PassText}>
            Password
          </label>
          <input
            type="password"
            id="pass"
            name="password"
            className={styles.pass}
            placeholder="******"
            required
          />

          <button type="submit" className={styles.button}>
            Log In
          </button>
        </form>
      </div>
    </>
  );
}
